### ISSUE TITLE
PotLock with NextJS

### ISSUE THREAD

**Issue by wpdas** [PotLock/potlock-nextjs-app#1]
- Project bootstrap: `nextjs, rematch (state manager), shadcn, tailwind, unocss, typescript, naxios, wallet-selector, react-query, initial contracts, initial api services, eslint, prettier, initial hooks, initial store, initial pages.` ✅
 - Project structure: ✅
 - Projects Page: 
 - Donate Randomly Modal: 
 - Profile Page 
 - Feed Page: 
 - Pots Home Page: 
 - Pot Single Page: 
 - Donors Page: 
 - Cart Page:
 - Homepage filter: 
 - Donor Leaderboard: 
 - Create Project Page: 
 - Edit Project Page:
 - Deploy Pot:

Notes:
- use [**Zod**](https://www.npmjs.com/package/zod) for form schema validation
- use [**React Hook Form**](https://react-hook-form.com/) to handle forms. Use [**React Hook Form -> Resolvers**](https://github.com/react-hook-form/resolvers) to implement Zod along with React Hook Form.

Ref links:

[**Figma**](https://www.figma.com/file/OHnvTSKflKjEQYbizmwB2q/Potlock-V2?type=design&node-id=0-1&mode=design&t=kdFBjyn7YXZpaGdc-0)
[**Repository**](https://github.com/PotLock/potlock-nextjs-app)

Map:
✅ = Done
🕵️ = Tested

**Comment by codingshot** [comment]
is this task still needed?

**Comment by carina-akaia** [comment]
@codingshot no ( CC @wpdas )
