### ISSUE TITLE
[FEATURE] Edit Lists

### ISSUE THREAD

**Issue by codingshot** [PotLock/potlock-nextjs-app#102]
- [x] update list if admin or owner
- [x] can add or remove people easily from list (not sure if we have design)
- [x] can edit lists details
- [x] owners can add or remove admins (admins cannot)
- [x] show list success screen on creation

potlock.org/figma 
Lists on Figma https://potlock.org/figma-lists
Lists Contract https://potlock.org/list-docs

![Edit List](https://github.com/user-attachments/assets/2bdad507-91dd-4ab3-96ce-316fa19181e4)
[Uploading potlistsmobile.zip…]()

**Comment by harjaapdhillon16** [comment]
<img width="1440" alt="Screenshot 2024-08-12 at 03 53 18" src="https://github.com/user-attachments/assets/11b6654e-508f-4ebf-a7e8-9e79687dce25">
Added the create list success , but how are we gonna show it as there is a redirect from the wallet page

**Comment by Ebube111** [comment]
Done
