### ISSUE TITLE
[FEATURE] My Favorite Lists

### ISSUE THREAD

**Issue by codingshot** [PotLock/potlock-nextjs-app#104]
Their is a upvote that indicates your favorites and hleper function on list contract ot query this. This is a filter on explore page for lists, similar in UX to #103 

- Ability to view my favorites by most recent favorites
<img width="641" alt="" src="https://github.com/user-attachments/assets/b714a3cd-e15b-4be7-bca5-1e264d87c121">

In future adding filter to favorites would be nice

https://potlock.org/figma-list
https://potlock.org/list-docs

**Comment by Ebube111** [comment]
Done
