### ISSUE TITLE
[FEATURE] Approve Projects on list

### ISSUE THREAD

**Issue by codingshot** [PotLock/potlock-nextjs-app#108]
Where admins and owners can change status for proejcts on lists and see applications with context

- [ ] change status with a dropdown
- [ ] ability to change multiple statuses at once
- [ ] shows applications differently

Not sure if design exists for this, consult emmaneul

Docs on List https://potlock.org/list-docs
Lists on Figma https://potlock.org/figma-list

**Comment by Ebube111** [comment]
Done
