### ISSUE TITLE
[FEATURE] List Page

### ISSUE THREAD

**Issue by codingshot** [PotLock/potlock-nextjs-app#109]
Page where list exists

- [ ] for admins and owners can go to #102 button popups up
- [ ] Shows all proejcts on lists
- [ ] Ability to filter based on status
- [ ] Ability to appy if application is open 
- [ ] see admins
- [ ] Donate to all
- [ ] Donate popup modal
- [ ] share list w/ referral link (pass in accountid in share link in referrer props (ask @carina-akaia on how this is done for donations)
- [ ] when click on people goes to project or profile page
<img width="740" alt="" src="https://github.com/user-attachments/assets/87bbef4d-947d-4032-a974-85628f71848b">

https://potlock.org/list-docs
https://potlock.org/figma-list

**Comment by Ebube111** [comment]
Done
