### ISSUE TITLE
[FEATURE] Create Campaign

### ISSUE THREAD

**Issue by codingshot** [PotLock/potlock-nextjs-app#110]
- [ ] accessible from campaign home page
- [ ] ability to create campaign
- [ ] optional min amount
- [ ] require date if min amount
- [ ] optional start date, start date starts automaticall

----
Campaign Docs https://potlock.org/campaign-docs
Campaign Figma https://potlock.org/figma-campaign

**Comment by Ebube111** [comment]
Done
