### ISSUE TITLE
[BUG]Frequent Error When Attempting to Donate on Alpha Potlock

### ISSUE THREAD

**Issue by Amichael10** [PotLock/potlock-nextjs-app#162]
I have noticed a recurring issue when trying to donate on the Potlock web app (https://alpha.potlock.io). After I am prompted to sign the message in my wallet, an error message consistently appears. This problem requires me to repeatedly click "Approve" or wait several minutes before I can successfully complete the donation process.

**To Reproduce**
- Go to https://alpha.potlock.io.
- Select a donation option and proceed to donate.
- When prompted, sign the message in your wallet.
- Observe that an error message appears immediately after signing.
- Attempt to click "Approve" multiple times or wait for a few minutes before the donation is processed.
**Screenshots**

![Screen Shot 2024-10-09 at 2 13 20 PM](https://github.com/user-attachments/assets/32258c91-6486-419a-9894-87c70ae1134a)

**Comment by carina-akaia** [comment]
Turned out to be a protocol infrastructure issue, we can't really do anything about it
