### ISSUE TITLE
[BUG] Create./Dev pot not available in alpha #181

### ISSUE THREAD

**Issue by 0xcrans** [PotLock/potlock-nextjs-app#234]
**Describe the bug**
Cannot make a donation or fund the pot via alpha.potlock.io | nearian.v1.potfactory.potlock.near unavailable 
**To Reproduce**
1. Go to https://alpha.potlock.io/pot/nearian.v1.potfactory.potlock.near/projects?donateToPot=nearian.v1.potfactory.potlock.near
2. Click on donate
3. See error that no pot is available 
    - even when you choose a project manually you can see NEAR Retro Builders and MDAO pot, no feature to donate directly via create./dev pot

![image](https://github.com/user-attachments/assets/3173a0d1-34b0-4f37-9179-51fc2de975ce)

![image](https://github.com/user-attachments/assets/70cfb90b-fd9f-4401-b2af-f88a894017af)

**Comment by carina-akaia** [comment]
@0xcrans the issue should be gone now, could you please check if I haven't missed anything? As a precaution, I'd recommend to clear your browser cache

**Comment by 0xcrans** [comment]
> @0xcrans the issue should be gone now, could you please check if I haven't missed anything? As a precaution, I'd recommend to clear your browser cache first

`Donation to Projects in CREATE./DEV` works well - first issue solved, however `Donation to [xyz]` doesn't work.

I've checked all accounts and seems that half of all projects have a such issue. Cases:
- beat-dao.sputnik-dao.near 
![image](https://github.com/user-attachments/assets/28f9f18a-7624-4bf2-99ea-5e4baadc4084)

- omegadigi-worlddao.sputnik-dao.near 
![image](https://github.com/user-attachments/assets/157fb416-4e9e-43fc-9813-4f1149c27025)

- survival-is-near.sputnik-dao.near
![image](https://github.com/user-attachments/assets/e83cc41a-32a3-4693-9550-f76db5c2f929)

- shitzu.sputnik-dao.near
![image](https://github.com/user-attachments/assets/a58122c8-a3fc-430b-bff9-0736981ca31b)

- gfxvs_artbattle.near
![image](https://github.com/user-attachments/assets/ac5a66ac-ebc5-4c30-b5f9-3e1ab6d14723)

- proofofvibes.near
![image](https://github.com/user-attachments/assets/941600b2-7177-400b-aed5-33a23a362a45)

**Comment by carina-akaia** [comment]
> `Donation to Projects in CREATE./DEV` works well - first issue solved, however `Donation to [xyz]` doesn't work.
> 
> I've checked all accounts and seems that half of all projects have a such issue.

Noted, I'll address this as well. We've had some indexer issues and this might be related.

**Comment by carina-akaia** [comment]
@0xcrans GM, we've reindexed pot applications, which should resolve the issue
