### ISSUE TITLE
Pot Applications: Update tab layout to fit the updated design and use indexer for data retrieval

### ISSUE THREAD

**Issue by carina-akaia** [PotLock/potlock-nextjs-app#254]
[|▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔[ 🎨 DESIGN REFERENCE ]▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔|](https://www.figma.com/design/ckixqGfuRKZ63tTvdJzi6j/Potlock?node-id=21876-36012&m=dev)

> [!IMPORTANT]
> The current implementation uses pot contract client function calls with primitive state management,
> which lacks automated cache management and reactivity, causing UX and performance issues.
> Thus, the scope of this task also covers the indexer integration.

Backend search is addressed in https://github.com/PotLock/django-indexer/issues/112

**Comment by Jikugodwill** [comment]
The new UI doesn't have a search bar, so search isn't probably needed here?
