### ISSUE TITLE
Donors Page: Donors Leaderboard

### ISSUE THREAD

**Issue by M-Rb3** [PotLock/potlock-nextjs-app#43]
Reference:[ https://app.potlock.org/?tab=donors](https://app.potlock.org/?tab=donors)
Implement top 3 card

**Comment by carina-akaia** [comment]
Closed in favor of the WIP duplicate ticket https://github.com/PotLock/potlock-nextjs-app/issues/161

**Comment by carina-akaia** [comment]
Closed in favor of the WIP duplicate ticket https://github.com/PotLock/potlock-nextjs-app/issues/161
